server:
  port: 8083
  servlet:
    context-path: /auth

spring:
  application:
    name: ms-auth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/auth?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: 123mudar

#configuração do spring security
security:
  jwt:
    token:
      secret-key: chave_microservices # key assinatura do token
      exprires-length: 360000 # tempo de expiração