server:
  port: 8081
  servlet:
    context-path: /crud

spring:
  application:
    name: ms-crud
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/crud?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: 123mudar

  # configuração do RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

# keys values para configuração do routing-key e do exchange do RabbitMQ
crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.produto.routingkey

#configuração do spring security
security:
  jwt:
    token:
      secret-key: chave_microservices # key assinatura do token